### ISSUE TITLE
How to validate CSW schema

### ISSUE THREAD

**Issue by arthurgustin** [terminalstatic/go-xsd-validate#1]
Hi,
I currently develop a CSW API (OGC norm). I found 0 libraries for xsd validation in golang, so for now my program validates xsd using a process call to libxml2, it works but this is a temporary solution.

Example: 

```
xmllint --noout --nocompact --nsclean --schema http://schemas.opengis.net/cat/csw/3.0/cswAll.xsd
```
When xmllint encounters an unknown schema, it fetches it on the internet. I bypassed those connexions by setting up a local server on port 80 and adding schemas.opengis.net on /etc/hosts.

In brief, it works but it sucks.

So, I was glad to find your library today, but it doesn't seem to work for my use case, and I get the following error: `Xsd parser error` which is not very developer-friendly.

Here is a non-working sample code:

```
import (
    xsd "github.com/terminalstatic/go-xsd-validate"
)

func myFunction() {
        xsd.Init()
	defer xsd.Cleanup()
	xsdhandler, err := xsd.NewXsdHandlerUrl("/path/to/schemas.opengis.net/cat/csw/3.0/cswAll.xsd", xsd.ParsErrDefault)
	if err != nil {
		panic("handleUrl " + err.Error())
	}

	xmlhandler, err := xsd.NewXmlHandlerMem(input, xsd.ParsErrDefault)
	if err != nil {
		panic("handleMem " + err.Error())
	}
	defer xmlhandler.Free()

	err = xsdhandler.Validate(xmlhandler, xsd.ValidErrDefault)
	if err != nil {
		panic("Validate " + err.Error())
	}
}
```

The code panics at `xsd.NewXsdHandlerUrl(...)`

Anyway, what do you recommand for this case ? Do I need to register every schemas ? How do I get better errors message ?

Thanks

**Comment by terminalstatic** [comment]
Hi arthur, thanks for reporting this, I only tested with xsd files for that's my use case. It looks like that when using http urls the errno gets set by libxml which messes up the return value. I added the reset of errno after the parse, didn't really test it though (in a hurry) ... the xsd schema dump looks ok so it *should* be working now.

**Comment by terminalstatic** [comment]
On a side note, disregarding the bug, you can turn on verbose parsing messages with the option ParsErrVerbose (xsd.NewXmlHandlerMem(input, xsd.ParsErrVerbose)), you shouldn't do this if performance and concurrency is an issue ... it slows the parsing down considerably. My guess is some kind of mutex handling in the libxml lib, I didn't really check the source though.
