### ISSUE TITLE
Getting issue in installation

### ISSUE THREAD

**Issue by nikhilbhavsar121** [terminalstatic/go-xsd-validate#16]
Hello,
I'm tring to compare xsd with xml but getting error while installation. Can you please suggest the solution.

Before
![image](https://github.com/terminalstatic/go-xsd-validate/assets/43513556/56cd211f-8c0a-42b9-8a28-e92399516665)
After go get
![image](https://github.com/terminalstatic/go-xsd-validate/assets/43513556/6b280729-1033-4365-afa6-4f049f3b6464)
In debug
![image](https://github.com/terminalstatic/go-xsd-validate/assets/43513556/2359ba2d-5ff3-46a8-ae58-fcf5ce415ece)

**Comment by terminalstatic** [comment]
Probably install C build tools, pkg-config in particular and/or put it into the PATH variable.

**Comment by nikhilbhavsar121** [comment]
Thanks.. 

sudo apt-get update
sudo apt-get install pkg-config
After this two cmd in debugger is working and code is working fine.

But in production docker failing
![image](https://github.com/terminalstatic/go-xsd-validate/assets/43513556/b3aae493-645c-4c41-9bf9-4b58ba31a23f)

this is docker file
![image](https://github.com/terminalstatic/go-xsd-validate/assets/43513556/740dd0a7-723d-4707-8094-7b6bdc80bef6)

it's failing After this cmd 
RUN cd $APP_DIR && CGO_ENABLED=0 go build -ldflags '-d -w -s' -v

Please suggest any change required in docker file or in above cmd

**Comment by terminalstatic** [comment]
Sorry I really can't help you out there. I'd guess CGO_ENABLED=0 is probably not such a good idea when using cgo and an external c library, but in the end you'd have to figure this out yourself for your specific use case.
