### ISSUE TITLE
Deprecation Warning for xmlSchemaCleanupTypes in libxml2

### ISSUE THREAD

**Issue by Tonny-Francis** [terminalstatic/go-xsd-validate#21]
I am currently using the go-xsd-validate library and noticed a deprecation warning for the function xmlSchemaCleanupTypes when compiling my project:

```go
warning: 'xmlSchemaCleanupTypes' is deprecated [-Wdeprecated-declarations]

```

**Comment by terminalstatic** [comment]
Thanks, there was actually a pull request I recently merged into master that fixes this, but unfortunately I was not able to test the changes yet, so it's not tagged. Therefore if you want to try it you'd have to get master.

**Comment by Tonny-Francis** [comment]
Ok, thanks
