### ISSUE TITLE
Error: malloc_trim

### ISSUE THREAD

**Issue by rhernandez-itemsoft** [terminalstatic/go-xsd-validate#4]
**Error:  github.com\terminalstatic\go-xsd-validate\libxml2.go line 480
unknow C.malloc_trim(0)**
i replace by C.malloc(0) and build 

Windows 8.1 x64
MinGW-W64-builds-4.3.5 - install preferences:  
mingw-w64
64bits
posix
sjlj
![image](https://user-images.githubusercontent.com/4327356/57556978-16407380-733e-11e9-96c3-5b25d4dea916.png)

**Comment by terminalstatic** [comment]
Hi,
Thanks for reporting this. 
I'd actually recommend commentig this out altogether for the basic intention behind this was compacting memory. As a quick internet search revealed that this function seems to not being available on all platforms  I'll probably remove it to not cause compilation problems. I'd also recon that scheduling gc and memory trimming is rarely really necessary.
