### ISSUE TITLE
element omitempty  not work

### ISSUE THREAD

**Issue by rhernandez-itemsoft** [terminalstatic/go-xsd-validate#5]
element, omitempty - it does not work
When I want to omit an element that is empty so that it is not shown in the XML, this library continues to validate the element and indicates "his element is not expected."

![imagen](https://user-images.githubusercontent.com/4327356/57721352-93732d80-7649-11e9-9820-da97986260d4.png)

**Comment by terminalstatic** [comment]
What you do in go's struct has no relation to the librarys validation functions.
To validate this struct you'd have to first unmarshall it (using go's library functions). If this is what you do you'd possibly have to check your xsd definition and maybe have to update the minOccurs attribute accordingly.
