### ISSUE TITLE
Question: Split xsd - functionality <xs:import>

### ISSUE THREAD

**Issue by Stegosawr** [terminalstatic/go-xsd-validate#9]
Does the validation work with split xsd files? For example you have one main xsd file that references other xsd files using 
xs:import

This is commonly used in Germany for xsd validation of e-invoices.
I attached 4 xsd files and one example xml file to be validated.

[XSD-Test.zip](https://github.com/terminalstatic/go-xsd-validate/files/5048049/XSD-Test.zip)

**Comment by terminalstatic** [comment]
As from my experience and tests (I'm splitting up xsd definitions into multiple files aswell for my apis) this works as expected.
In general all you'd have to do is to use your "main" definition file as the first parameter for NewXsdHandlerUrl.
You can easily try if this works for you, just use https://github.com/terminalstatic/go-xsd-validate/blob/master/examples/_server/simpler/simpler.go and modify accordingly. You can use a local file path too.
That being said I hand off loading and parsing to libxml2 so all the magic happens there.

**Comment by Stegosawr** [comment]
I just tested it out on a ubuntu vm and it seems to work fine :)
Thanks and keep up the good work.
